[package]
name = "bgfastnet_lib"
version = "0.1.0"
edition = "2021"
description = "A Rust library for decoding the FastNet protocol used by B&G Hydra / H2000 instruments"
license = "MIT"
repository = "https://github.com/ghotihook/rust-bgfastnet-lib"
documentation = "https://docs.rs/bgfastnet_lib"
readme = "README.md"
keywords = ["bng", "fastnet", "marine", "nmea", "signalk"]
categories = ["science::robotics", "hardware-support::embedded"]
authors = ["ghotihook <github.com/ghotihook>"]

[dependencies]
log = "0.4"

[dev-dependencies]
criterion = "0.5"